# Generated by Django 2.2.14 on 2020-07-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
